name: dbt-build
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: ./ci_profile

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - name: Create dbt profile for DuckDB
        run: |
          mkdir -p "$DBT_PROFILES_DIR"
          cat > "$DBT_PROFILES_DIR/profiles.yml" <<'YAML'
          dbt_dublinbikes:
            outputs:
              dev:
                type: duckdb
                path: warehouse.duckdb
            target: dev
          YAML
      - run: dbt deps
      - run: python scripts/ingest_dublinbikes.py
      - run: dbt build --select tag:realtime
